baseURL = 'https://example.org/'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'Overseas Living'

[languages.cn]
contentDir = 'content/cn'
disabled = false
languageCode = 'zh-CN'
languageDirection = 'ltr'
languageName = 'Chinese'
title = '奥维斯(第二家园)有限公司'

[languages.jp]
contentDir = 'content/jp'
disabled = false
languageCode = 'ja-JP'
languageDirection = 'ltr'
languageName = 'Japanese'
title = 'オーバーシーズ リビング株式会社'



[menu]

[[menu.main]]
name = 'Home'
url = '#home'
weight = 1

[[menu.main]]
name = 'Services & Content'
url = '#content'
weight = 2

[[menu.main]]
name = 'Why Malaysia?'
url = '#emm2h'
weight = 3

[[menu.main]]
name = 'FAQs'
url = '#faqs'
weight = 4

[[menu.main]]
name = 'Contact'
url = '#contact'
weight = 5
